added check

diff --git a/.github/workflows/get_name_and_version.yml b/.github/workflows/get_name_and_version.yml
--- a/.github/workflows/get_name_and_version.yml
+++ b/.github/workflows/get_name_and_version.yml
@@ -23,16 +23,36 @@ jobs:
           pip install mlflow
           pip install jinja2
 
-      - name: Print current working directory
-        run: pwd
-
       - name: Read info.md and pass to main.py
         run: |
           if [ -f src/Data/name_version.md ]; then
             CONTENT=$(cat src/Data/name_version.md)
             echo "File content: $CONTENT"
-            #echo "$CONTENT" > input.txt  # Scrive il contenuto in un file temporaneo
             python src/main.py "$(printf '%s' "$CONTENT")" 
+          else
+            echo "File src/Data/name_version.md not found!"
+            exit 1
+          fi
+
+      - name: test pass
+        run: |
+          if [ -f src/Data/name_version.md ]; then
+            CONTENT=$(cat src/Data/name_version.md)
+            echo "File content: $CONTENT"
+            
+            # Esegui lo script Python e cattura il codice di uscita
+            if python src/main.py "$(printf '%s' "$CONTENT")"; then
+              echo "No exceptions"
+            else
+              COMMENT="$CONTENT: No model in Model Registry"
+              PR_NUMBER=${{ github.event.pull_request.number }}
+              PR_NUMBER=${{ github.event.pull_request.number }}
+              curl -X POST \
+                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+                -H "Accept: application/vnd.github.v3+json" \
+                https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments \
+                -d "{\"body\":\"$COMMENT\"}"
+            fi
           else
             echo "File src/Data/name_version.md not found!"
             exit 1
